import json
import math
inp=open("data.json","r")
outp=open("data.php","w")

data = json.load(inp)
inp.close()

outp.write("<?php \n")
outp.write("//automaticaly generated by submap/python tordeles/jsontophp.py\n")
def saveArray(name):
	outp.write("$%s=Array(" % (name));
	outerFirst=True
	for tomb in data[name]:
		if not outerFirst:
			outp.write(",")
		else:
			outerFirst=False
		outp.write("Array(");
		first=True
		for a in tomb:
			if not first:
				outp.write(",")
			else:
				first=False
			outp.write( "Array(%f,%f)" % (a[0],a[1]) )
		outp.write(")");
	outp.write(");\n");
print data.keys();
for key in data.keys():
	saveArray(key)

outp.close()
